### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iveksl2**

### CODE REVIEW

**Comment by iveksl2** [comment]
@nloadholtes & @berzhy i learned this from you, approve? : ) Now i guess i will just have to do it :(

**Comment by berzhy** [comment]
> @nloadholtes & @berzhy i learned this from you, approve? : ) Now i guess i will just have to do it :(

Yeah, they might be useful. Let's try formulating them, but without being too fanatical :)

Nice links btw!

**Review by berzhy — APPROVED** [review]

**Comment by iveksl2** [comment]
@berzhy to formalize you mean do this in our processes when i create specs?

**Comment by berzhy** [comment]
> @berzhy to formalize you mean do this in our processes when i create specs?

Lets try in one of the future specs and see if it's feasible and improves understanding?

**Pull request merged**
